# Generated by Django 4.2.23 on 2025-08-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_movie_delete_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dscription',
            field=models.TextField(),
        ),
    ]
