# Generated by Django 4.2.23 on 2025-08-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_movie_dscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='film_image/')),
                ('name', models.CharField(max_length=155)),
                ('description', models.TextField(null=True)),
                ('direct_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.TextField(null=True)),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
