# Generated by Django 5.2.5 on 2025-08-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_janr_category_film_category_janr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_category',
        ),
    ]
