# Generated by Django 5.2.5 on 2025-12-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_category_name_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='films', to='app.janr'),
        ),
    ]
