# Generated by Django 5.2.5 on 2025-12-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_film_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='admin_films', to='app.janr'),
        ),
        migrations.CreateModel(
            name='UserFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='film_image/')),
                ('name', models.CharField(max_length=155)),
                ('description', models.TextField(null=True)),
                ('direct_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.TextField(null=True)),
                ('duration', models.CharField(max_length=20)),
                ('genres', models.ManyToManyField(blank=True, related_name='user_films', to='app.janr')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='user_film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userfilm'),
        ),
    ]
