# Generated by Django 5.2.5 on 2025-12-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_category_user_film_film_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
