# Generated by Django 5.2.5 on 2025-12-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
