# Generated by Django 5.2.5 on 2025-12-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_film_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='description',
        ),
        migrations.RemoveField(
            model_name='film',
            name='name',
        ),
        migrations.AddField(
            model_name='film',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='film',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Name (Russian)'),
        ),
        migrations.AddField(
            model_name='film',
            name='name_uz',
            field=models.CharField(default='', max_length=255, verbose_name='Name (Uzbek)'),
        ),
    ]
