# Generated by Django 5.2.5 on 2025-12-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_film_description_remove_film_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Russian)'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Uzbek)'),
        ),
    ]
