# Generated by Django 5.2.5 on 2025-12-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_film_description_en_alter_film_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='film',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='film',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='film',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='film',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='film',
            name='name_uz',
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='name',
            field=models.CharField(default='Film 1', max_length=155),
            preserve_default=False,
        ),
    ]
