# Generated by Django 5.2.5 on 2026-01-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_film_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
