# Generated by Django 5.2.5 on 2026-01-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_public',
            new_name='is_anonymous',
        ),
    ]
