# Generated by Django 5.2.5 on 2026-01-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_public',
        ),
    ]
